/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

/**
 *
 * @author victoire
 */
public class MushroomForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MushroomForm.class.getName());

    /**
     * Creates new form MushroomForm
     */
    public MushroomForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblResult = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnIdentify = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        chkGills = new javax.swing.JCheckBox();
        chkForest = new javax.swing.JCheckBox();
        chkRing = new javax.swing.JCheckBox();
        chkConvex = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel1.setText("MushroomForm");

        lblResult.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblResult.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        lblResult.setPreferredSize(new java.awt.Dimension(200, 22));

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel2.setText("Result:");

        btnIdentify.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnIdentify.setText("Identify");
        btnIdentify.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnIdentify.addActionListener(this::btnIdentifyActionPerformed);

        btnSave.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnSave.setText("Save");
        btnSave.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnSave.addActionListener(this::btnSaveActionPerformed);

        btnExit.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnExit.setText("Exit");
        btnExit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnExit.addActionListener(this::btnExitActionPerformed);

        chkGills.setText("Has gills?");

        chkForest.setText("Grows in forest?");
        chkForest.addActionListener(this::chkForestActionPerformed);

        chkRing.setText("Has ring?");
        chkRing.addActionListener(this::chkRingActionPerformed);

        chkConvex.setText("Convex cap?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(261, 261, 261))
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(btnIdentify)
                .addGap(126, 126, 126)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSave)
                        .addGap(116, 116, 116)
                        .addComponent(btnExit)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(288, 288, 288))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkConvex)
                            .addComponent(chkRing)
                            .addComponent(chkForest)
                            .addComponent(chkGills))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chkGills)
                .addGap(35, 35, 35)
                .addComponent(chkForest)
                .addGap(39, 39, 39)
                .addComponent(chkRing)
                .addGap(26, 26, 26)
                .addComponent(chkConvex)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIdentify)
                    .addComponent(btnSave)
                    .addComponent(btnExit))
                .addContainerGap(186, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            boolean gills = chkGills.isSelected();
            boolean forest = chkForest.isSelected();
            boolean ring = chkRing.isSelected();
            boolean convex = chkConvex.isSelected();

            String name = lblResult.getText();

            model.Mushroom m = new model.Mushroom(name, gills, forest, ring, convex);

            dao.MushroomDAO dao = new dao.MushroomDAO();
            dao.save(m);

            javax.swing.JOptionPane.showMessageDialog(this, "Saved!");

            } catch (Exception e) {
                e.printStackTrace();
}
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnIdentifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIdentifyActionPerformed
        boolean gills = chkGills.isSelected();
        boolean forest = chkForest.isSelected();
        boolean ring = chkRing.isSelected();
        boolean convex = chkConvex.isSelected();

        String result = util.MushroomLogic.identify(gills, forest, ring, convex);

        lblResult.setText(result);
    }//GEN-LAST:event_btnIdentifyActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void chkForestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkForestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkForestActionPerformed

    private void chkRingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkRingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkRingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MushroomForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnIdentify;
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox chkConvex;
    private javax.swing.JCheckBox chkForest;
    private javax.swing.JCheckBox chkGills;
    private javax.swing.JCheckBox chkRing;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField lblResult;
    // End of variables declaration//GEN-END:variables
}
